---
micronaut:
    application:
        name: micronaut-jaeger-graal
jackson:
  module-scan: false
  bean-introspection-module: true

---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1